<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>assets\launcher-icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="lzo.net">
      <HintPath>vendor\package_9.3.3\package\Resources\BinariesNET8\lzo.net.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="vendor\**" />
    <Compile Remove="tests\**" />
    <EmbeddedResource Remove="vendor\**" />
    <None Remove="vendor\**" />
  </ItemGroup>
  <ItemGroup Condition="Exists('artifacts\cnc-speed\ddraw.dll')">
    <Content Include="artifacts\cnc-speed\ddraw.dll" Link="native-runtime\ddraw.dll" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="artifacts\cnc-speed\LICENSE.cnc-ddraw.txt" Link="native-runtime\LICENSE.cnc-ddraw.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="artifacts\cnc-speed\LICENSE.Detours.txt" Link="native-runtime\LICENSE.Detours.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
